# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_MACH_EXYNOS9810_CROWNLTE_EUR_OPEN) :=  \
    exynos9810-crownlte_eur_open_17.dtb \
    exynos9810-crownlte_eur_open_18.dtb \
    exynos9810-crownlte_eur_open_19.dtb \
    exynos9810-crownlte_eur_open_21.dtb \
    exynos9810-crownlte_eur_open_23.dtb \
    exynos9810-crownlte_eur_open_24.dtb \
    exynos9810-crownlte_eur_open_25.dtb \
    exynos9810-crownlte_eur_open_26.dtb
dtb-$(CONFIG_MACH_EXYNOS9810_STARLTE_EUR_OPEN) :=  \
    exynos9810-starlte_eur_open_16.dtb \
    exynos9810-starlte_eur_open_17.dtb \
    exynos9810-starlte_eur_open_18.dtb \
    exynos9810-starlte_eur_open_20.dtb \
    exynos9810-starlte_eur_open_23.dtb \
    exynos9810-starlte_eur_open_26.dtb
dtb-$(CONFIG_MACH_EXYNOS9810_STAR2LTE_EUR_OPEN) :=  \
    exynos9810-star2lte_eur_open_16.dtb \
    exynos9810-star2lte_eur_open_17.dtb \
    exynos9810-star2lte_eur_open_18.dtb \
    exynos9810-star2lte_eur_open_20.dtb \
    exynos9810-star2lte_eur_open_23.dtb \
    exynos9810-star2lte_eur_open_26.dtb

# dtb-$(CONFIG_MACH_EXYNOS9810_CROWNLTE_KOR) :=
# dtb-$(CONFIG_MACH_EXYNOS9810_STARLTE_KOR) :=
# dtb-$(CONFIG_MACH_EXYNOS9810_STAR2LTE_KOR) :=

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
