# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_MACH_EXYNOS9810_CROWNLTE_EUR_OPEN) :=  \
    exynos9810-crownlte_eur_open_26.dtb
# dtb-$(CONFIG_MACH_EXYNOS9810_CROWNLTE_KOR) :=
# dtb-$(CONFIG_MACH_EXYNOS9810_STARLTE_KOR) :=
# dtb-$(CONFIG_MACH_EXYNOS9810_STAR2LTE_KOR) :=

always            := $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files       := *.dtb*
